site:
    title:        Bacardi55 front page
    description:  My front page on the internet
    author_name:  Bacardi55
    author_email: admin@bacardi55.org
    author_url:   http://bacardi55.org

engine:
    themes: %dir%/vendor/carew/theme-bootstrap
    extensions:
        - Carew\Plugin\Toc\TocExtension
        - Carew\Plugin\Highlight\HighlightExtension
