site:
    title:        bacardi55's blog
    author_name:  bacardi55
    author_email: admin@bacardi55.org
    author_url:   http://bacardi55.org

engine:
    themes: %dir%/vendor/carew/theme-bootstrap
    extensions:
        - Carew\Plugin\Highlight\HighlightExtension
